[package]
name = "mathematics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.31.0"
plotters = "0.3.5"
walkdir = "2.4.0"
chrono = "0.4.30"